"""與 `/api/cases/coverage-matrix` 共用之 SQL 片段（請保持與歷史巡檢邏輯同步）。"""

from __future__ import annotations

from typing import Any

CASE_INV_FRESH_TS = (
    "COALESCE(NULLIF(TRIM(c.updated_at), ''), "
    "NULLIF(TRIM(s.last_checked_at), ''), "
    "NULLIF(TRIM(s.crawled_at), ''))"
)

CASE_INV_JP_LISTING_SQL = "COALESCE(NULLIF(TRIM(s.content_kind), ''), '') = 'jp_listing'"


def coverage_host_where_sql(host: str) -> tuple[str, list[Any]]:
    hk = str(host or "").strip().lower()
    if hk == "yes1.co.jp":
        return (
            "(instr(lower(COALESCE(s.item_url,'')),'yes1.co.jp')>0 "
            "OR instr(lower(COALESCE(s.item_url,'')),'yes-station')>0)",
            [],
        )
    if hk == "oheya-su.jp":
        return (
            "(instr(lower(COALESCE(s.item_url,'')),'oheya-su.jp')>0 "
            "OR instr(lower(COALESCE(s.item_url,'')),'oheyasuu.com')>0 "
            "OR instr(lower(COALESCE(s.item_url,'')),'oheyago.jp')>0)",
            [],
        )
    return ("instr(lower(COALESCE(s.item_url,'')), ?) > 0", [hk])


def coverage_region_where_sql(region_label: str) -> tuple[str, list[Any]]:
    r = str(region_label or "").strip()
    if not r:
        return ("1=1", [])
    region_aliases: dict[str, tuple[str, ...]] = {
        "首都圏": (
            "首都圏",
            "首都圈",
            "/tokyo/",
            "/tokyo_sc",
            "/kanagawa/",
            "/saitama/",
            "/chiba/",
            "東京",
            "東京都",
            "神奈川",
            "横浜",
            "横滨",
            "川崎",
            "埼玉",
            "千葉",
            "さいたま",
            "/yokohama/",
            "/kawasaki/",
            "/tokyo_23ku/",
            "tokyo_23ku",
            "chuko/tokyo",
            "shinchiku/tokyo",
            # 與「東京」列對齊：僅標題含 23 區表記、無「東京」字面時，須仍算首都圏
            "23区",
            "２３区",
            # Yahoo! 不動産 關東 used/mansion/search 路徑代碼（詳情頁常無 /tokyo/）
            "search/03/",
            "/03/11",
            "/03/12",
            "/03/13",
            "/03/14",
        ),
        "關東": (
            "關東",
            "関東",
            "/kanto/",
            "/tokyo/",
            "/tokyo_sc",
            "/kanagawa/",
            "/saitama/",
            "/chiba/",
            "東京",
            "東京都",
            "神奈川",
            "横浜",
            "横滨",
            "川崎",
            "埼玉",
            "千葉",
            "/yokohama/",
            "/kawasaki/",
            "/tokyo_23ku/",
            "chuko/tokyo",
            "shinchiku/tokyo",
            "23区",
            "２３区",
            "search/03/",
            "/03/11",
            "/03/12",
            "/03/13",
            "/03/14",
        ),
        "關西": (
            "關西",
            "関西",
            "/kansai/",
            "/osaka/",
            "/kyoto/",
            "/hyogo/",
            "大阪",
            "大阪府",
            "大阪市",
            "京都",
            "京都府",
            "京都市",
            "兵庫",
            "兵庫県",
            "神戸",
            "奈良",
            "滋賀",
            "和歌山",
            "search/06/",
            "/06/27",
            "/06/26",
            "/06/28",
            "/area-25/",
            "/area-26/",
            "/area-27/",
            "/area-28/",
            "/area-29/",
            "/area-30/",
            "/line-25/",
            "/line-26/",
            "/line-27/",
            "/line-28/",
            "/line-29/",
            "/line-30/",
        ),
        "北海道": ("北海道", "/hokkaido/", "/hokkaido_sc"),
        "東北": (
            "東北",
            "青森",
            "岩手",
            "宮城",
            "仙台",
            "秋田",
            "山形",
            "福島",
            "/tohoku/",
            "/aomori/",
            "/iwate/",
            "/miyagi/",
            "/akita/",
            "/yamagata/",
            "/fukushima/",
            "/area-2/",
            "/area-3/",
            "/area-4/",
            "/area-5/",
            "/area-6/",
            "/area-7/",
            "/line-2/",
            "/line-3/",
            "/line-4/",
            "/line-5/",
            "/line-6/",
            "/line-7/",
        ),
        "甲信越": (
            "甲信越",
            "山梨",
            "長野",
            "新潟",
            "/koshinetsu/",
            "/yamanashi/",
            "/nagano/",
            "/niigata/",
            "/area-15/",
            "/area-19/",
            "/area-20/",
            "/line-15/",
            "/line-19/",
            "/line-20/",
        ),
        "北陸": (
            "北陸",
            "富山",
            "石川",
            "福井",
            "/hokuriku/",
            "/toyama/",
            "/ishikawa/",
            "/fukui/",
            "/area-16/",
            "/area-17/",
            "/area-18/",
            "/line-16/",
            "/line-17/",
            "/line-18/",
        ),
        "東海": (
            "東海",
            "愛知",
            "名古屋",
            "静岡",
            "岐阜",
            "三重",
            "/tokai/",
            "/aichi/",
            "/gifu/",
            "/mie/",
            "/shizuoka/",
            "/nagoya/",
            "/area-21/",
            "/area-22/",
            "/area-23/",
            "/area-24/",
            "/line-21/",
            "/line-22/",
            "/line-23/",
            "/line-24/",
        ),
        "中國地方": (
            "中國地方",
            "中国地方",
            "広島",
            "廣島",
            "岡山",
            "山口",
            "島根",
            "鳥取",
            "/chugoku/",
            "/hiroshima/",
            "/okayama/",
            "/yamaguchi/",
            "/shimane/",
            "/tottori/",
            "/area-31/",
            "/area-32/",
            "/area-33/",
            "/area-34/",
            "/area-35/",
            "/line-31/",
            "/line-32/",
            "/line-33/",
            "/line-34/",
            "/line-35/",
        ),
        "四國": (
            "四國",
            "四国",
            "徳島",
            "德島",
            "香川",
            "愛媛",
            "高知",
            "/shikoku/",
            "/kagawa/",
            "/ehime/",
            "/kochi/",
            "/tokushima/",
            "/area-36/",
            "/area-37/",
            "/area-38/",
            "/area-39/",
            "/line-36/",
            "/line-37/",
            "/line-38/",
            "/line-39/",
        ),
        "九州": (
            "九州",
            "福岡",
            "熊本",
            "長崎",
            "鹿児島",
            "宮崎",
            "佐賀",
            "大分",
            "北九州",
            "/kyushu/",
            "/fukuoka/",
            "/kumamoto/",
            "/nagasaki/",
            "/kagoshima/",
            "/oita/",
            "/miyazaki/",
            "/saga/",
            "/area-40/",
            "/area-41/",
            "/area-42/",
            "/area-43/",
            "/area-44/",
            "/area-45/",
            "/area-46/",
            "/line-40/",
            "/line-41/",
            "/line-42/",
            "/line-43/",
            "/line-44/",
            "/line-45/",
            "/line-46/",
        ),
        "沖繩": ("沖繩", "沖縄", "那覇", "/okinawa/", "/okinawa_sc", "/area-47/", "/line-47/"),
        "東京": (
            "東京",
            "東京都",
            "/tokyo/",
            "/tokyo_sc",
            "chuko/tokyo",
            "/tokyo_23ku/",
            "tokyo_23ku",
            "shinchiku/tokyo",
            "23区",
            "２３区",
        ),
        "大阪": ("大阪", "大阪府", "大阪市", "/osaka/", "/osaka_sc", "chuko/osaka"),
        "名古屋": ("名古屋", "愛知", "/nagoya/", "/aichi/"),
        "福岡": ("福岡", "福岡県", "福岡市", "/fukuoka/", "/fukuoka_sc", "chuko/fukuoka"),
        "神奈川": ("神奈川", "横浜", "川崎", "/kanagawa/", "/kanagawa_sc", "/yokohama/", "/kawasaki/"),
        "埼玉": ("埼玉", "さいたま", "/saitama/", "/saitama_sc", "chuko/saitama"),
        "千葉": ("千葉", "/chiba/", "/chiba_sc", "chuko/chiba"),
        "横滨": ("横滨", "横浜", "/yokohama/"),
        "川崎": ("川崎", "/kawasaki/"),
        "京都市": ("京都市", "京都府", "/kyoto/", "/kyoto_sc"),
    }
    parts = [
        "instr(COALESCE(c.case_jp_region_override,''), ?) > 0",
        "instr(COALESCE(c.title_zh_hant,''), ?) > 0",
        "instr(COALESCE(c.title_zh_hans,''), ?) > 0",
        "instr(COALESCE(c.body_zh_hant,''), ?) > 0",
        "instr(COALESCE(c.body_zh_hans,''), ?) > 0",
        "instr(COALESCE(s.title_original,''), ?) > 0",
        "instr(COALESCE(s.body_original,''), ?) > 0",
        "instr(COALESCE(s.item_url,''), ?) > 0",
    ]
    params = [r] * len(parts)
    for tok in region_aliases.get(r, ()):
        st = str(tok or "").strip()
        if not st:
            continue
        if "/" in st:
            parts.append("instr(lower(COALESCE(s.item_url,'')), ?) > 0")
            params.append(st.lower())
        else:
            parts.append("instr(COALESCE(s.title_original,''), ?) > 0")
            parts.append("instr(COALESCE(s.body_original,''), ?) > 0")
            parts.append("instr(COALESCE(c.title_zh_hant,''), ?) > 0")
            parts.append("instr(COALESCE(c.body_zh_hant,''), ?) > 0")
            params.extend([st, st, st, st])
    return ("(" + " OR ".join(parts) + ")", params)


# 與 coverage-heal／scripts/fill_matrix_min10／app._coverage_heal_region_queries 共用之地區關鍵字擴展。
COVERAGE_HEAL_REGION_QUERY_ALIASES: dict[str, tuple[str, ...]] = {
    "首都圏": ("首都圏", "首都圈", "関東", "關東", "東京", "神奈川", "埼玉", "千葉"),
    "關東": ("關東", "関東", "東京", "神奈川", "埼玉", "千葉"),
    "關西": ("關西", "関西", "大阪", "京都", "兵庫", "京都市"),
    "北海道": ("北海道", "札幌", "hokkaido", "sapporo"),
    "東北": ("東北", "仙台", "宮城", "青森", "岩手", "秋田", "山形", "福島", "tohoku"),
    "甲信越": ("甲信越", "長野", "新潟", "山梨", "yamanashi", "niigata", "nagano"),
    "北陸": ("北陸", "富山", "石川", "福井", "hokuriku", "toyama", "ishikawa"),
    "東海": ("東海", "愛知", "名古屋", "岐阜", "三重", "静岡", "shizuoka", "aichi", "gifu", "mie"),
    "中國地方": ("中國地方", "中国地方", "広島", "岡山", "山口", "島根", "鳥取", "hiroshima", "okayama"),
    "四國": ("四國", "四国", "香川", "愛媛", "高知", "徳島", "tokushima", "kagawa"),
    "九州": ("九州", "福岡", "熊本", "長崎", "鹿児島", "宮崎", "佐賀", "大分", "kyushu", "kumamoto"),
    "沖繩": ("沖繩", "沖縄", "okinawa", "那覇"),
    "東京": ("東京", "東京都", "tokyo"),
    "大阪": ("大阪", "大阪府", "osaka"),
    "名古屋": ("名古屋", "愛知", "aichi", "nagoya"),
    "福岡": ("福岡", "福岡県", "fukuoka"),
    "神奈川": ("神奈川", "横浜", "横滨", "川崎", "kanagawa", "yokohama", "kawasaki"),
    "横滨": ("横滨", "横浜", "yokohama"),
    "川崎": ("川崎", "kawasaki"),
    "埼玉": ("埼玉", "さいたま", "saitama"),
    "千葉": ("千葉", "chiba"),
    "京都市": ("京都市", "京都府", "京都", "kyoto"),
}
